(ns riscv_cpu.actor
  "riscv_cpu clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). CPU core microarchitecture design (RISC-V ISA).

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; CpuCore
   {:db/ident :riscv_cpu.CpuCore/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.CpuCore/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/isa :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/microarch :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/frequencyGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/issueWidth :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CpuCore/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Pipeline
   {:db/ident :riscv_cpu.Pipeline/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.Pipeline/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Pipeline/stages :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Pipeline/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Pipeline/branchPredictor :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Pipeline/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Pipeline/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; RegisterFile
   {:db/ident :riscv_cpu.RegisterFile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.RegisterFile/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.RegisterFile/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.RegisterFile/count :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.RegisterFile/widthBits :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.RegisterFile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.RegisterFile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; CacheLevel
   {:db/ident :riscv_cpu.CacheLevel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.CacheLevel/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/level :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/sizeKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/associativity :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/latencyCycles :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.CacheLevel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; IsaExtension
   {:db/ident :riscv_cpu.IsaExtension/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.IsaExtension/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.IsaExtension/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.IsaExtension/version :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.IsaExtension/ratified :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.IsaExtension/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.IsaExtension/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Microbench
   {:db/ident :riscv_cpu.Microbench/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :riscv_cpu.Microbench/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Microbench/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Microbench/ipc :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Microbench/scoreType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Microbench/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :riscv_cpu.Microbench/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"CpuCore" "Pipeline" "RegisterFile" "CacheLevel" "IsaExtension" "Microbench"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "riscv_cpu: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "riscv_cpu: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "riscv_cpu: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── CpuCore ────────────────────────────────────────────────────────────────
(defn create-cpu-core
  "Create a CpuCore."
  [port data]
  (require-fields data ["name" "isa"])
  (let [id (new-id "cpu_cpu")
        e {:db/id id
           :riscv_cpu.CpuCore/id id
           :riscv_cpu.CpuCore/name (get data :name)
           :riscv_cpu.CpuCore/isa (get data :isa)
           :riscv_cpu.CpuCore/microarch (get data :microarch)
           :riscv_cpu.CpuCore/frequencyGhz (as-double (get data :frequencyGhz))
           :riscv_cpu.CpuCore/issueWidth (as-long (get data :issueWidth))
           :riscv_cpu.CpuCore/createdAt (now)
           :riscv_cpu.CpuCore/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cpu-cores
  "List CpuCore with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cpu-cores port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.CpuCore/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.CpuCore/name :riscv_cpu.CpuCore/isa :riscv_cpu.CpuCore/microarch :riscv_cpu.CpuCore/frequencyGhz :riscv_cpu.CpuCore/issueWidth])]
     (paginate rows opts))))

(defn get-cpu-core
  "Retrieve a CpuCore by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cpu-core port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cpu-core
  "Update a CpuCore; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :riscv_cpu.CpuCore/name (get data :name)]))
                   (cond-> (contains? data :isa) (conj [:db/add id :riscv_cpu.CpuCore/isa (get data :isa)]))
                   (cond-> (contains? data :microarch) (conj [:db/add id :riscv_cpu.CpuCore/microarch (get data :microarch)]))
                   (cond-> (contains? data :frequencyGhz) (conj [:db/add id :riscv_cpu.CpuCore/frequencyGhz (as-double (get data :frequencyGhz))]))
                   (cond-> (contains? data :issueWidth) (conj [:db/add id :riscv_cpu.CpuCore/issueWidth (as-long (get data :issueWidth))]))
                   (conj [:db/add id :riscv_cpu.CpuCore/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cpu-core
  "Delete a CpuCore."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Pipeline ────────────────────────────────────────────────────────────────
(defn create-pipeline
  "Create a Pipeline."
  [port data]
  (require-fields data ["stages" "type"])
  (let [id (new-id "cpu_pip")
        e {:db/id id
           :riscv_cpu.Pipeline/id id
           :riscv_cpu.Pipeline/coreId (get data :coreId)
           :riscv_cpu.Pipeline/stages (as-long (get data :stages))
           :riscv_cpu.Pipeline/type (get data :type)
           :riscv_cpu.Pipeline/branchPredictor (get data :branchPredictor)
           :riscv_cpu.Pipeline/createdAt (now)
           :riscv_cpu.Pipeline/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-pipelines
  "List Pipeline with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-pipelines port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.Pipeline/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.Pipeline/coreId :riscv_cpu.Pipeline/stages :riscv_cpu.Pipeline/type :riscv_cpu.Pipeline/branchPredictor])]
     (paginate rows opts))))

(defn get-pipeline
  "Retrieve a Pipeline by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-pipeline port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-pipeline
  "Update a Pipeline; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :riscv_cpu.Pipeline/coreId (get data :coreId)]))
                   (cond-> (contains? data :stages) (conj [:db/add id :riscv_cpu.Pipeline/stages (as-long (get data :stages))]))
                   (cond-> (contains? data :type) (conj [:db/add id :riscv_cpu.Pipeline/type (get data :type)]))
                   (cond-> (contains? data :branchPredictor) (conj [:db/add id :riscv_cpu.Pipeline/branchPredictor (get data :branchPredictor)]))
                   (conj [:db/add id :riscv_cpu.Pipeline/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-pipeline
  "Delete a Pipeline."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── RegisterFile ────────────────────────────────────────────────────────────────
(defn create-register-file
  "Create a RegisterFile."
  [port data]
  (require-fields data ["kind" "count"])
  (let [id (new-id "cpu_reg")
        e {:db/id id
           :riscv_cpu.RegisterFile/id id
           :riscv_cpu.RegisterFile/coreId (get data :coreId)
           :riscv_cpu.RegisterFile/kind (get data :kind)
           :riscv_cpu.RegisterFile/count (as-long (get data :count))
           :riscv_cpu.RegisterFile/widthBits (as-long (get data :widthBits))
           :riscv_cpu.RegisterFile/createdAt (now)
           :riscv_cpu.RegisterFile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-register-files
  "List RegisterFile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-register-files port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.RegisterFile/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.RegisterFile/coreId :riscv_cpu.RegisterFile/kind :riscv_cpu.RegisterFile/count :riscv_cpu.RegisterFile/widthBits])]
     (paginate rows opts))))

(defn get-register-file
  "Retrieve a RegisterFile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-register-file port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-register-file
  "Update a RegisterFile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :riscv_cpu.RegisterFile/coreId (get data :coreId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :riscv_cpu.RegisterFile/kind (get data :kind)]))
                   (cond-> (contains? data :count) (conj [:db/add id :riscv_cpu.RegisterFile/count (as-long (get data :count))]))
                   (cond-> (contains? data :widthBits) (conj [:db/add id :riscv_cpu.RegisterFile/widthBits (as-long (get data :widthBits))]))
                   (conj [:db/add id :riscv_cpu.RegisterFile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-register-file
  "Delete a RegisterFile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── CacheLevel ────────────────────────────────────────────────────────────────
(defn create-cache-level
  "Create a CacheLevel."
  [port data]
  (require-fields data ["level" "sizeKb"])
  (let [id (new-id "cpu_cac")
        e {:db/id id
           :riscv_cpu.CacheLevel/id id
           :riscv_cpu.CacheLevel/coreId (get data :coreId)
           :riscv_cpu.CacheLevel/level (get data :level)
           :riscv_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))
           :riscv_cpu.CacheLevel/associativity (as-long (get data :associativity))
           :riscv_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))
           :riscv_cpu.CacheLevel/createdAt (now)
           :riscv_cpu.CacheLevel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cache-levels
  "List CacheLevel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cache-levels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.CacheLevel/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.CacheLevel/coreId :riscv_cpu.CacheLevel/level :riscv_cpu.CacheLevel/sizeKb :riscv_cpu.CacheLevel/associativity :riscv_cpu.CacheLevel/latencyCycles])]
     (paginate rows opts))))

(defn get-cache-level
  "Retrieve a CacheLevel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cache-level port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cache-level
  "Update a CacheLevel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :riscv_cpu.CacheLevel/coreId (get data :coreId)]))
                   (cond-> (contains? data :level) (conj [:db/add id :riscv_cpu.CacheLevel/level (get data :level)]))
                   (cond-> (contains? data :sizeKb) (conj [:db/add id :riscv_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))]))
                   (cond-> (contains? data :associativity) (conj [:db/add id :riscv_cpu.CacheLevel/associativity (as-long (get data :associativity))]))
                   (cond-> (contains? data :latencyCycles) (conj [:db/add id :riscv_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))]))
                   (conj [:db/add id :riscv_cpu.CacheLevel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cache-level
  "Delete a CacheLevel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── IsaExtension ────────────────────────────────────────────────────────────────
(defn create-isa-extension
  "Create a IsaExtension."
  [port data]
  (require-fields data ["name" "version"])
  (let [id (new-id "cpu_isa")
        e {:db/id id
           :riscv_cpu.IsaExtension/id id
           :riscv_cpu.IsaExtension/coreId (get data :coreId)
           :riscv_cpu.IsaExtension/name (get data :name)
           :riscv_cpu.IsaExtension/version (get data :version)
           :riscv_cpu.IsaExtension/ratified (as-bool (get data :ratified))
           :riscv_cpu.IsaExtension/createdAt (now)
           :riscv_cpu.IsaExtension/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-isa-extensions
  "List IsaExtension with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-isa-extensions port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.IsaExtension/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.IsaExtension/coreId :riscv_cpu.IsaExtension/name :riscv_cpu.IsaExtension/version :riscv_cpu.IsaExtension/ratified])]
     (paginate rows opts))))

(defn get-isa-extension
  "Retrieve a IsaExtension by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-isa-extension port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-isa-extension
  "Update a IsaExtension; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :riscv_cpu.IsaExtension/coreId (get data :coreId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :riscv_cpu.IsaExtension/name (get data :name)]))
                   (cond-> (contains? data :version) (conj [:db/add id :riscv_cpu.IsaExtension/version (get data :version)]))
                   (cond-> (contains? data :ratified) (conj [:db/add id :riscv_cpu.IsaExtension/ratified (as-bool (get data :ratified))]))
                   (conj [:db/add id :riscv_cpu.IsaExtension/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-isa-extension
  "Delete a IsaExtension."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Microbench ────────────────────────────────────────────────────────────────
(defn create-microbench
  "Create a Microbench."
  [port data]
  (require-fields data ["name" "ipc"])
  (let [id (new-id "cpu_mic")
        e {:db/id id
           :riscv_cpu.Microbench/id id
           :riscv_cpu.Microbench/coreId (get data :coreId)
           :riscv_cpu.Microbench/name (get data :name)
           :riscv_cpu.Microbench/ipc (as-double (get data :ipc))
           :riscv_cpu.Microbench/scoreType (get data :scoreType)
           :riscv_cpu.Microbench/createdAt (now)
           :riscv_cpu.Microbench/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-microbenches
  "List Microbench with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-microbenches port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :riscv_cpu.Microbench/id))
         rows (apply-filters rows (:filter opts) [:riscv_cpu.Microbench/coreId :riscv_cpu.Microbench/name :riscv_cpu.Microbench/ipc :riscv_cpu.Microbench/scoreType])]
     (paginate rows opts))))

(defn get-microbench
  "Retrieve a Microbench by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-microbench port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-microbench
  "Update a Microbench; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :riscv_cpu.Microbench/coreId (get data :coreId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :riscv_cpu.Microbench/name (get data :name)]))
                   (cond-> (contains? data :ipc) (conj [:db/add id :riscv_cpu.Microbench/ipc (as-double (get data :ipc))]))
                   (cond-> (contains? data :scoreType) (conj [:db/add id :riscv_cpu.Microbench/scoreType (get data :scoreType)]))
                   (conj [:db/add id :riscv_cpu.Microbench/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-microbench
  "Delete a Microbench."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/cpucores" :op :create :entity "CpuCore"}
   {:method "GET" :path "/v1/cpucores" :op :list :entity "CpuCore"}
   {:method "GET" :path "/v1/cpucores/:id" :op :get :entity "CpuCore"}
   {:method "PATCH" :path "/v1/cpucores/:id" :op :update :entity "CpuCore"}
   {:method "DELETE" :path "/v1/cpucores/:id" :op :delete :entity "CpuCore"}
   {:method "POST" :path "/v1/pipelines" :op :create :entity "Pipeline"}
   {:method "GET" :path "/v1/pipelines" :op :list :entity "Pipeline"}
   {:method "GET" :path "/v1/pipelines/:id" :op :get :entity "Pipeline"}
   {:method "PATCH" :path "/v1/pipelines/:id" :op :update :entity "Pipeline"}
   {:method "DELETE" :path "/v1/pipelines/:id" :op :delete :entity "Pipeline"}
   {:method "POST" :path "/v1/registerfiles" :op :create :entity "RegisterFile"}
   {:method "GET" :path "/v1/registerfiles" :op :list :entity "RegisterFile"}
   {:method "GET" :path "/v1/registerfiles/:id" :op :get :entity "RegisterFile"}
   {:method "PATCH" :path "/v1/registerfiles/:id" :op :update :entity "RegisterFile"}
   {:method "DELETE" :path "/v1/registerfiles/:id" :op :delete :entity "RegisterFile"}
   {:method "POST" :path "/v1/cachelevels" :op :create :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels" :op :list :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels/:id" :op :get :entity "CacheLevel"}
   {:method "PATCH" :path "/v1/cachelevels/:id" :op :update :entity "CacheLevel"}
   {:method "DELETE" :path "/v1/cachelevels/:id" :op :delete :entity "CacheLevel"}
   {:method "POST" :path "/v1/isaextensions" :op :create :entity "IsaExtension"}
   {:method "GET" :path "/v1/isaextensions" :op :list :entity "IsaExtension"}
   {:method "GET" :path "/v1/isaextensions/:id" :op :get :entity "IsaExtension"}
   {:method "PATCH" :path "/v1/isaextensions/:id" :op :update :entity "IsaExtension"}
   {:method "DELETE" :path "/v1/isaextensions/:id" :op :delete :entity "IsaExtension"}
   {:method "POST" :path "/v1/microbenches" :op :create :entity "Microbench"}
   {:method "GET" :path "/v1/microbenches" :op :list :entity "Microbench"}
   {:method "GET" :path "/v1/microbenches/:id" :op :get :entity "Microbench"}
   {:method "PATCH" :path "/v1/microbenches/:id" :op :update :entity "Microbench"}
   {:method "DELETE" :path "/v1/microbenches/:id" :op :delete :entity "Microbench"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"cpucores" {:create create-cpu-core :list list-cpu-cores :get get-cpu-core :update update-cpu-core :delete delete-cpu-core}
   "pipelines" {:create create-pipeline :list list-pipelines :get get-pipeline :update update-pipeline :delete delete-pipeline}
   "registerfiles" {:create create-register-file :list list-register-files :get get-register-file :update update-register-file :delete delete-register-file}
   "cachelevels" {:create create-cache-level :list list-cache-levels :get get-cache-level :update update-cache-level :delete delete-cache-level}
   "isaextensions" {:create create-isa-extension :list list-isa-extensions :get get-isa-extension :update update-isa-extension :delete delete-isa-extension}
   "microbenches" {:create create-microbench :list list-microbenches :get get-microbench :update update-microbench :delete delete-microbench}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "riscv_cpu-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
